### ISSUE TITLE
Looking forward to the code release !

### ISSUE THREAD

**Issue by plyfager** [autonomousvision/projected_gan#1]
Great job! Can't wait to know the implementation details.

**Comment by xl-sr** [comment]
my plan is the end of this month / early December :)

**Comment by Vermeille** [comment]
Please publish the code already. Literally nobody care if it's not clean or of it is hacky.
Whatever is the work you think you have to do, you don't. The whole point of GitHub is not to be a gallery of clean and perfect code, but a hub for working on code and projects in progress.

There also is a growing trend of ML papers claiming code release with git repositories remaining empty forever.

And some people may want to try out your algorithm. Your paper has been out very recently, people may have already forgotten about it in two weeks, and you would be missing out feedbacks and citations.

**Comment by 0three** [comment]
Hah, this project is tooooooooo attractive!

**Comment by xl-sr** [comment]
Don't worry, our lab has a strong record of actually releasing code.
I'll stick with my schedule, I hope you won't have forgotten the paper until then 😉

**Comment by dome272** [comment]
> Please publish the code already. Literally nobody care if it's not clean or of it is hacky. Whatever is the work you think you have to do, you don't. The whole point of GitHub is not to be a gallery of clean and perfect code, but a hub for working on code and projects in progress.

I made a working (hacky and probably not even close to optimal) implementation which you could check out as long as their code is not out :)
