### ISSUE TITLE
Questions about "ngf"

### ISSUE THREAD

**Issue by Ian-Goodall-Halliwell** [autonomousvision/projected_gan#13]
Hello! 

It was mentioned in a previous post that one could decrease memory use by:

 "[reducing] the size of the FastGAN generator, e.g., set ngf=64"

I understand this decreases the size of the network layers, but will this have a noticeable effect on mid-resolution datasets (512p)? I am trying it regardless and will update with results, I was just wondering if anyone else has tried.

**Comment by xl-sr** [comment]
Setting ngf=128 yields the best FID generally, but the difference is small and depending on the dataset it might not even matter. We aimed to not change any hyperparameters across all datasets, so it is likely that you can still find more efficient settings for your specific case.
