### ISSUE TITLE
The parameters of scratch network are random.

### ISSUE THREAD

**Issue by PeterouZh** [autonomousvision/projected_gan#16]
Hi, great work!

![image](https://user-images.githubusercontent.com/26176709/145027181-f302c636-1aec-4455-9e3f-22ab03727496.png)
![image](https://user-images.githubusercontent.com/26176709/145027282-529b2c1f-3f74-4e67-aa11-caad62c7b642.png)

It seems that the scratch network is not updated. Could you explain it?

**Comment by xl-sr** [comment]
Hi :)

```self.scratch``` are random projections that mix features across scales and channels. 

As we explain in the paper (Section 3.2):

 "Common to both strategies is that they mix features using differentiable random projections which are fixed, i.e., after random initialization, the parameters of these layers are not trained.
