### ISSUE TITLE
FastGAN grid artifacts

### ISSUE THREAD

**Issue by JCBrouwer** [autonomousvision/projected_gan#17]
I've been noticing quite a lot of griddy/repetitive patterns in the outputs when training at high resolution with FastGAN.

Will the change from today help address those? Or are these inherent to the skip-excitation layers? (the grids do seem to be ~32x32, which is what is skipped to the 512x512 block). Alternatively, would you happen to know ways that these patterns could be reduced?

Example training grid with repetitive grid patterns (5000 image dataset after 919 kimg):

![training grid with repetitive grid patterns](https://i.imgur.com/eBlzs0i.jpg)

Example training grid with repetitive grid patterns and mode collapse (4000 image dataset after 680 kimg finetuning from above checkpoint)

![training grid with repetitive grid patterns (and mode collapse)](https://i.imgur.com/cwOeW7o.jpeg)

**Comment by JCBrouwer** [comment]
Alright, thanks for the quick reply! I'll fire up some runs with StyleGAN then.

By 'don't use the skip-excitation layers,' do you mean essentially making the FastGAN generator an nn.Sequential of UpBlockComp()'s? Is this a configuration you've tested?

**Comment by xl-sr** [comment]
Yes, that's exactly what I mean :) I did some testing and adding skip-excitation layers usually gave some minor improvements, so I kept them and didn't bother.

**Comment by xl-sr** [comment]
gonna close this for now, feel free to reopen it or to post updates :)

**Comment by JCBrouwer** [comment]
I've given both stylegan2 and the sequential fastgan a try, but haven't been happy with the results from either.

Here's the stylegan2 backend after 1000 kimg, serious mode collapse since the beginning of training:
![Training grid of projected GAN with stylegan2 backend. serious mode collapse is visibile in repeated structural patterns throughout the grid](https://i.imgur.com/cZ5MpUA.jpeg)

Sequential fastGAN had even worse grid / diagonal artifacts than regular fastGAN (comparable/slightly worse than separable discriminator version?) and wasn't able to get off the ground. ~300 kimg

![training grid with sequential fastgan, griddy diagonal artifacts](https://i.imgur.com/KuXnkZR.jpeg)

For reference here's the same dataset trained with essentially the CIFAR10 config of stylegan2-ada-pytorch (no PL reg, lower gamma, no style mixing), finetuned from the FFHQ checkpoint for 1000 kimg. There's also a little bit of mode collapse visible, but much less than the projected GAN version.

![stylegan2-ada-pytorch training grid, best quality overall with minor structural mode collapse](https://i.imgur.com/7OGLEaq.jpeg)

I'd say overall the regular projected FastGAN config is the most successful, but cannot quite reach the same artifactless quality as stylegan2-ada-pytorch.

**Comment by xl-sr** [comment]
very interesting, thanks for the insights!

Generally, we have seen that the current PG config might not be optimal for higher resolutions. As you can see in the results , the FIDs for higher resolution, e.g for Pokemon, are generally a bit higher (of course the task is also harder). This is likely due to the training resolution of the feature network being different, usually, it is at 224/256.

As a check, have you tried training on 256?
