### ISSUE TITLE
Questions about discriminator

### ISSUE THREAD

**Issue by yxhhxy7** [autonomousvision/projected_gan#19]
Hi. Thanks for your amazing work!

Why do you choose to use simple convolutional architecture as discriminators? For convergence speed? If the model will perform better when stronger discriminators are used?

**Comment by xl-sr** [comment]
hey :) what do you mean by stronger discriminators?

**Comment by yxhhxy7** [comment]
Like using the discriminator of fastgan instead of the simple convolutional architecture you are using now.

**Comment by xl-sr** [comment]
FastGAN is using a convolutional architecture as well. The main difference is that FastGAN uses are reconstruction loss on the discriminator's features for regularization. Projected GAN does not need additional regularization, hence, there is no advantage in adding a reconstruction loss.

**Comment by yxhhxy7** [comment]
I see. Thanks for your quick reply.
