### ISSUE TITLE
Conditional GANS

### ISSUE THREAD

**Issue by FilipAndersson245** [autonomousvision/projected_gan#2]
Hello,
Do you see any limitations in trying to apply this for conditional gans? 
I am looking into style transfer using gans. If when released please make it simple to apply to other areas, as I understand when skimming the paper most of the power is in the Discriminator correct?

**Comment by xl-sr** [comment]
Hi Filip, the release will include a conditional version, it is fairly straight-forward to implement :)

**Comment by FilipAndersson245** [comment]
Great, cannot wait to test it out 😃
