### ISSUE TITLE
Why don't use ADA in this implementation?

### ISSUE THREAD

**Issue by shampooooo** [autonomousvision/projected_gan#21]
I tried both diffaug and ADA in other stylegan2 model, and the performance when using ADA was better.

Do you think it's better to use fastgan than to use ADA due to lack of data?

Or because of the following problems?
https://github.com/lucidrains/stylegan2-pytorch/issues/223#issuecomment-922794046
https://github.com/NVlabs/stylegan2-ada-pytorch/issues/175#issue-989112485

**Comment by xl-sr** [comment]
You can also use ADA with FastGAN if you wanted to. But, we tried both, and usually, diffaug would return slightly better results.
So the standard setting is: PG + diffaug + FastGAN/StyleGAN2 generator

**Comment by shampooooo** [comment]
WOW! speed answer! thanks 👍
