### ISSUE TITLE
When will the Pretrained Model be published

### ISSUE THREAD

**Issue by BEaN001** [autonomousvision/projected_gan#23]
Hi, great job from you guys!

I notice that Projected GAN got Global Rank #1 with most datasets, but most datasets are 256*256, I wonder wether you guys will provide pretrained model on high-resolution dataset such as FFHQ 1024*1024 with both fastgan version and stylegan2 version.
It will be very useful for guys like me because of limited computation and data.  :)

by the way I also notice that when we save best model, the code is only for metric fid50k_full. 0.0
 # save best fid ckpt
            snapshot_pkl = os.path.join(run_dir, f'best_model.pkl')
            cur_nimg_txt = os.path.join(run_dir, f'best_nimg.txt')
            if rank == 0:
                if 'fid50k_full' in stats_metrics and stats_metrics['fid50k_full'] < best_fid:
                    best_fid = stats_metrics['fid50k_full']

                    with open(snapshot_pkl, 'wb') as f:
                        dill.dump(snapshot_data, f)
                    # save curr iteration number (directly saving it to pkl leads to problems with multi GPU)
                    with open(cur_nimg_txt, 'w') as f:
                        f.write(str(cur_nimg))

**Comment by xl-sr** [comment]
hi :) It is planned to release the models we evaluated in the paper in the coming weeks. If I get around to doing it, I might add more, eg. FFHQ 1024x1024.

Calculating ```fid50k_full``` is the standard (also in the original StyleGAN code base), but feel free to change it to smaller sample sizes, eg. 10k to speed up the evaluation.
