### ISSUE TITLE
Network snapshot saving in Colab not working

### ISSUE THREAD

**Issue by Escapado** [autonomousvision/projected_gan#24]
Hey guys!

Last night I got to try out your colab version of the project and started training with my own dataset. The results are amazing and by far outperform my results with stylegan2 (at a fraction of training time) so kudos to you! 
However, while the network properly saves sample images to my google drive folder every 10 ticks, it does not save any network pickles and I am at a loss as to why it doesn't.

Do you have any hints for me?

**Comment by xl-sr** [comment]
glad you're enjoying our work! It should save the latest weights at every snap in ```network-snapshot.pkl``` (I updated this last night). Maybe you tried it before I updated it?

**Comment by Escapado** [comment]
Wow that was fast and actually solved my problem. `launch_training()` and `train()` were updated, right? Now it saves a `.pkl` in the same folder. Thank you so much!

**Comment by jlmarrugom** [comment]
Hi, 
I'm reopening this issue by asking if the resume from .pkl could be applied between different folders or runs.

I've trained a model with a dataset and want to continue training it with a different dataset but loading a model from a different folder to continue training, but it simply doesn't work, the model starts the training process from scratch.

Do you have any tips on this?

**Comment by woctezuma** [comment]
This is how StyleGAN has been coded.
