### ISSUE TITLE
Issue replicating published numbers

### ISSUE THREAD

**Issue by Susmit-A** [autonomousvision/projected_gan#26]
Hi,

I'm having some trouble replicating the published numbers on the Pokemon set. My runs converge to an FID of about 29. While some variance from published numbers is expected, this is quite a large difference. I'm not sure why this is happening, as I've not changed the code or training parameters. Could you kindly provide some insights?

Thanks

**Comment by xl-sr** [comment]
what are your training settings exactly?

**Comment by Susmit-A** [comment]
I used the exact same code as commit [edc3720](https://github.com/autonomousvision/projected_gan/tree/edc3720681b3eef3ed69cd5a658cc17d1360f4bc). Other specs are as following:
- System: Ubuntu 18.04
- GPU: Quadro RTX 8000 (x2)
- Batch Size: 64

- #ticks: 350 (1.4 MImgs)

FID progress plot 
![1463a3d4-0dc3-4547-9523-34233eaadff5](https://user-images.githubusercontent.com/17704685/145953704-f4a2a0bc-4306-4e30-8186-8e9a81292695.jpg)

Plot for an older commit, with lowest FID 28.6 (4.5 MImgs):
![67f449c4-a661-43d9-97be-eeeb37963688](https://user-images.githubusercontent.com/17704685/145953843-9e7a4274-f5c2-4f26-ba76-3a5c5c96afaa.jpg)

**Comment by xl-sr** [comment]
In edc3720 I increased the capacity of the generator which leads to much better results on diverse and large datasets (FFHQ  LSUN). However, this seems to be counterproductive on small datasets such as Pokemon. I added a new option (```--cfg=fastgan_lite```) which uses a light weight generator that trains faster and gives better results. You should be able to reproduce our results from the paper, below is the FID curve that I get with the most recent commit (8480bdd), best FID=26.27.

![image](https://user-images.githubusercontent.com/29833625/145972495-6ae50cdb-a48c-44a7-903c-b96d75fbafcf.png)
