### ISSUE TITLE
Using Pretrained model

### ISSUE THREAD

**Issue by Fqlox** [autonomousvision/projected_gan#29]
Hi, 
First, thanks for this very cool project.

I wanted to use a pretrained model in (.pkl), I got from : [awesome-pretrained-stylegan2 ](https://github.com/justinpinkney/awesome-pretrained-stylegan2 ).
And I got :
`ImportError: cannot import name 'networks_stylegan2' from 'training' (unknown location)`

Is there a solution or should I train it myself ?

Thanks in advance

**Comment by xl-sr** [comment]
fixed it, thanks @woctezuma !

@Fqlox please reopen this issue if you still run into problems.

**Comment by CeciLyu** [comment]
Hi Axel,

Thanks for updating the code. I am running the version with the import fixed. I got a new error:

AttributeError: module 'pg_modules.networks_stylegan2' has no attribute 'Discriminator'

Do you have any suggetsion on how to fix this? @xl-sr 

Thanks
