### ISSUE TITLE
No improvement in speed of convergence

### ISSUE THREAD

**Issue by vanga** [autonomousvision/projected_gan#32]
Hi,

I have been experimenting SG2-ada, SG3 for my datasets of florals. I have had reasonable models trained on these datasets with OOTB hyper parameter settings. FIDs of 10-15. However, convergence isn't state of the art (could be because I haven't run the training for longer, typically for 1000-3000 kimg depending on if I used transfer learning or not). 

I came across Projected GAN paper and it is very interesting. However, I haven't seen any convergence improvements as mentioned in the paper. To me, the convergence performance more or less seems same as SG2-ada surprisingly when tried for about 1000-1500 kimg from scratch. I am wondering if there is something fundamentally different with my dataset that makes using pre trained model in discriminator architecture ineffective. Is it possible that the feature space of these pre trained models is not optimal for my datasets. Is there a way to verify that?

I have also observed comparatively high memory usage with PG training. I was able to run with 32 per-gpu-batch size with SG2 ada. However, I am able to run only 8 per-gpu-batch sizes with PG.

**More info**
Dataset: different types of florals
Size: 4.5k-6k
Dimensions: 256x256
Infra: V100, Google Colab
Config: FASTGAN
Floral type 1: 17 FID after training for 14 hours, 1400 kimg
Floral type 2: 36 FID after training for 11 hours 1000 kimg

For both these datasets, I got similar FIDs trained for similar range of kimgs on sg2-ada. Overall, there is probably slight improvement in convergence speed (maybe 1.5x), but not significant. 

I would be interested to know your thoughts on these observations. 

Thanks.

**Comment by xl-sr** [comment]
oh, that is interesting! 

It is likely not a limitation of the feature network, eg., Pokemon is also very different from F's training data.
The first thing you can try is the fastgan_lite config since your dataset is likely not very diverse (maybe you can post a few samples here). 

You can also easily try a different F, by adapting the code here 
https://github.com/autonomousvision/projected_gan/blob/8480bdd9150a44c31874ffa69835e10a4f6009c4/pg_modules/projector.py#L33
and here
https://github.com/autonomousvision/projected_gan/blob/8480bdd9150a44c31874ffa69835e10a4f6009c4/pg_modules/projector.py#L63

**Comment by vanga** [comment]
Hi, thanks for looking into this.
My intution is that pokemon data is simple to learn compared to mine. w.r.t the diversity, I would expect my data to be diverse, but I wonder if there is a way to quantify it to be sure.

Considering the same dataset size worked reasonably well with SG2-ada, I didn't think of trying fastgan_lite. Though, I don't have a 1-1 comparison with SG2-ada..its just my observation that there wasn't significant improvement. I could give fastgan_lite a try though.

w.r.t to using different F, to make sure that I understand, are you suggesting to use a different pre trained model(that's more specific to my dataset) instead of the one being used by default? 

Here are some sample images from my dataset
![99097f7918e3d283eca95fce850031ff--design-floral-floral-prints](https://user-images.githubusercontent.com/5126396/147646400-7f76b12a-07a4-47f7-afdd-ace09b3d8e7e.jpg)![09e295b2f1af4ebaa6ea87eece8b2927b16602ae](https://user-images.githubusercontent.com/5126396/147646404-9d0c2d2f-998b-4b98-8405-4a7ac5c7e5ed.jpg)![ffa5dbc3384bdacf60ac75f4f306523476edb4e4](https://user-images.githubusercontent.com/5126396/147646406-024dc145-4f4e-4e43-915d-8b2c9b49eb29.jpg)


![7496a24081bdaf7a65f6d9e2965e9f81031f1741](https://user-images.githubusercontent.com/5126396/147646492-21422dc0-8229-4d7b-84b3-0683f50e8bb2.jpg)![704bc227063df111df123229aed74bd6d3a9442b](https://user-images.githubusercontent.com/5126396/147646500-af4e98d7-e696-4a7b-9e06-c47e115ac2f4.jpg)![6f551b58558e579cebd02056cfa14434ffe4102a](https://user-images.githubusercontent.com/5126396/147646503-ec0c2674-0359-43b0-9769-6633e59278c0.jpg)

**Comment by xl-sr** [comment]
beautiful dataset :)

The samples are very texture-heavy, so I suspect that the deeper layers of F may actually hurt performance. The deeper features are more semantic and capture global shape, which in your case is not necessary.

My recommendations:
- give fastgan_lite a try
- use ```proj_type=1```. CSM helps to utilize deeper features better, but as stated above you likely do not need it. You can change this here: https://github.com/autonomousvision/projected_gan/blob/8480bdd9150a44c31874ffa69835e10a4f6009c4/train.py#L246
- Do not use discs on deeper features, ie, set ```num_discs =2 ``` https://github.com/autonomousvision/projected_gan/blob/8480bdd9150a44c31874ffa69835e10a4f6009c4/train.py#L247
- You may want to try patch discriminators, ie, add a line with ```c.D_kwargs.backbone_kwargs.patch = True```

**Comment by vanga** [comment]
Thanks for the pointers, I may not be able to get to try out these changes right away. So, I will close this issue and reopen if I have more questions once I try out these changes.
