### ISSUE TITLE
Mode Collapse on a New Dataset

### ISSUE THREAD

**Issue by benjaminklein** [autonomousvision/projected_gan#34]
Hi,

I'm getting Mode Collapse on a new dataset. I do see nice behavior on AFHQ. Which HyperParameters should I try to optimize in order to get it working on my dataset?

Thanks in advance @xl-sr

**Comment by xl-sr** [comment]
hey :) I will need more information to help you. What are you training settings? (you can post your ```training_options.json``` here). Also, what is your dataset like? Maybe you can post screenshots of a few samples.

**Comment by benjaminklein** [comment]
Hey! Thanks for the kind and quick response.

Attached are the settings. I tried 256x256 resolution. Nothing too special about the dataset. I also attached a few images.
[img000010.zip](https://github.com/autonomousvision/projected_gan/files/7790242/img000010.zip)
[training_options.zip](https://github.com/autonomousvision/projected_gan/files/7790243/training_options.zip)

Are there any HyperParameters that you usually tune for a new dataset? Like gamma in Pytorch-ADA?

**Comment by xl-sr** [comment]
the dataset seems fine. There is not eqivalent to gamma, we got all the results in the paper with the same hyperparameters, no tuning. But there are a few architectural changes you can try (in decreasing importance):
- Continue training. I don't know for how long you trained, but in some cases I first observed behaviour that looked like mode collapse but the samples diversify later in training
- try```--cfg=fastgan_lite```
- try```--cfg=stylegan2```, as noted in a related issue, FastGAN does not do very well on human face/body synthesis
- Increase the batch size eg. 256

If none of these options leads to better results, it might be that the current PG configuration is just not well suited to human body synthesis, eg. a specialized feature network might be needed.

**Comment by woctezuma** [comment]
> as noted in a related issue

#25
