### ISSUE TITLE
Information regarding FastGAN-Lite

### ISSUE THREAD

**Issue by johnsutor** [autonomousvision/projected_gan#36]
Do you plan on releasing any supplementary material discussing the efficacy of the FastGAN-Lite configuration? In particular, I'm curious as to how small of a dataset (i.e., <5k, <10k...) does the FastGAN-Lite perform better than the FastGAN model, and what batch sizes does the FastGAN-Lite perform the best at? Thank you!

**Comment by xl-sr** [comment]
No, releasing additional supplementary material is not planned, but in my experience, for anything <10k FastGAN_lite should give better/faster results. My recommendation for batch size has not changed, generally, it is best to use a total of 64 and 8/16 per GPU.

**Comment by johnsutor** [comment]
Thank you!
