### ISSUE TITLE
Something strange in training

### ISSUE THREAD

**Issue by LonglongaaaGo** [autonomousvision/projected_gan#38]
Hi Axel,
Thanks for your beautiful repo.
I tried your project, and add some modifications to this. 
But I found something weird. For FastGAN, I can train the model with batch=6 on the 8G 2080. But when I use the ProjectGAN in your code, I cannot run with even batch=1. 
Can you give me some advice for saving some space for training? (I use my model)

Thank you so much!
Best regards,
Wanglong

**Comment by xl-sr** [comment]
hi :) 

The first thing you should try is reducing the size of the generator, ie. set ngf=64 (the default of the original FastGAN) and use ```-cfg=fastgan_lite```.
