### ISSUE TITLE
Out of memory with batch  at 1

### ISSUE THREAD

**Issue by Fqlox** [autonomousvision/projected_gan#40]
Hi, I got an issue when training on a custom datatset, with fast gan I got a `RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 8.00 GiB total capacity; 5.92 GiB already allocated; 0 bytes free; 6.06 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF` when training.  
I reduced the batch size to one but I keep getting this error
the command : 
`python train.py --outdir=./output_models/ --cfg=fastgan --data=./mydata --gpus 1 --batch 1 --mirror 0 --snap 50 --batch-gpu=1 --kimg=50 --cond True`

the dataset is composed with 50k image at 256x256px.

I'm on windows 10 with a RTX 2070 (8 GB VRAM)

Hiw can I prevent that ?

Thanks in advance

**Comment by woctezuma** [comment]
- #5

**Comment by xl-sr** [comment]
see linked issues above
