### ISSUE TITLE
Installation without conda

### ISSUE THREAD

**Issue by CeciLyu** [autonomousvision/projected_gan#41]
Hi Axel,

Thank you for sharing the code for your article. I am trying to install and run the code on a HPC cluster where using conda is not adviced. 

Could you release a requirements.txt file, so that I can install the dependencies with pip? I am also happy to hear any other suggestions you might have. 

Thanks in advance!

**Comment by woctezuma** [comment]
- https://github.com/autonomousvision/projected_gan/issues/4#issuecomment-982990695

**Comment by xl-sr** [comment]
see linked issue above ;)
