### ISSUE TITLE
module 'pg_modules.networks_stylegan2' has no attribute 'Discriminator'

### ISSUE THREAD

**Issue by CeciLyu** [autonomousvision/projected_gan#43]
Hi Axel,

Thanks for updating the code. I am running the version with the import fixed. I got a new error:

AttributeError: module 'pg_modules.networks_stylegan2' has no attribute 'Discriminator'

Do you have any suggetsion on how to fix this? 

Thanks

_Originally posted by @xl-sr in https://github.com/autonomousvision/projected_gan/issues/29#issuecomment-1002523441_

**Comment by woctezuma** [comment]
Maybe it requires a fix similar to https://github.com/autonomousvision/projected_gan/commit/66dc9f92644fde571a6091dcecae64780f7b10d9.

**Comment by xl-sr** [comment]
jep, that is the solution :) where do you import ```Discriminator``` ?
