### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by GaParmar** [autonomousvision/projected_gan#48]
Hi, 

I am trying to generate samples with this method and reproduce the FID numbers reported in the paper. 
I was wondering if you could provide the pre-trained models that you use in the paper?

Regards,
Gaurav

**Comment by woctezuma** [comment]
Related:
- https://github.com/autonomousvision/projected_gan/issues/23#issuecomment-990736287

**Comment by xl-sr** [comment]
Hey, I was a bit occupied due to a recent deadline. I will be adding the models next week :)
