### ISSUE TITLE
Exporting trained model to onnx

### ISSUE THREAD

**Issue by Fqlox** [autonomousvision/projected_gan#49]
Hi, I tried to implement a onnx export of trained model. Following Pytorch doc, I wrote:

```
network_pkl = "model.pkl"

print('Loading networks from "%s"...' % network_pkl)
device = torch.device('cuda')
with dnnlib.util.open_url(network_pkl) as f:
    G = legacy.load_network_pkl(f)['G_ema'].to(device) # type: ignore
model = G

# Labels.
label = torch.zeros([1, G.c_dim], device=device)

# Export the model
torch.onnx.export(model,                            # model being run
                    label,                          # model input (or a tuple for multiple inputs)
                    "export.onnx",                  # where to save the model (can be a file or file-like object)
                    export_params=True,             # store the trained parameter weights inside the model file
                    opset_version=9,                # the ONNX version to export the model to
                    do_constant_folding=True,       # whether to execute constant folding for optimization
                    input_names = ['Latent'],       # the model's input names
                    output_names = ['Image']        # the model's output names
                    )
 
```

And I got : 
`TypeError: forward() missing 1 required positional argument: 'c'`

Can't figure out where the issues is.

Thanks in advance

**Note:**

The model trained is a fast gan lite conditional

**Comment by woctezuma** [comment]
It looks like the the class `c` argument is expected by `forward()`.

Not sure how to fix it, but you can see that the argument is dummy for the cases which are not conditional.

https://github.com/autonomousvision/projected_gan/blob/10ae1313823847a6d1780339c808d2cb7efbf560/pg_modules/discriminator.py#L51-L52

**Comment by xl-sr** [comment]
I didn't use onnx before, but it seems that currently you only feed in the  label as input:
```
 label,                          # model input (or a tuple for multiple inputs)
```
However, the generator expects a random latent vector z and a class label c (you can set this to None for an unconditional model).
