### ISSUE TITLE
Huggingface Spaces

### ISSUE THREAD

**Issue by AK391** [autonomousvision/projected_gan#51]
Hello, would you be interested in sharing a web demo on Huggingface Spaces for Projected GAN?

It would make this model more accessible as it would allow people to try out the model directly from the browser. Some other recent machine learning model repos have set up Spaces for easy access:

github: https://github.com/salesforce/BLIP
Spaces: https://huggingface.co/spaces/akhaliq/BLIP

github: https://github.com/facebookresearch/omnivore
Spaces: https://huggingface.co/spaces/akhaliq/omnivore

Spaces is completely free, and I can help setup a Gradio Space. Here are some getting started instructions if you'd prefer to do it yourself: https://huggingface.co/blog/gradio-spaces

**Comment by xl-sr** [comment]
Great idea! I'll be adding the pretrained models in the coming week, so then you could easily set it up :)

**Comment by AK391** [comment]
@xl-sr great, I setup a org under autonomousvision https://huggingface.co/autonomousvision, (same as github here) and can add you as a team member, will be easy to add other models like https://github.com/autonomousvision/stylegan_xl when they are ready under the same org :)

**Comment by xl-sr** [comment]
awesome, thanks!

**Comment by AK391** [comment]
@xl-sr forgot to add, when your ready just make a request to join the org and I can approve it

**Comment by AK391** [comment]
@xl-sr setup a template space for projected gan here https://huggingface.co/spaces/autonomousvision/projected_gan once the pretrained models are ready I can update

**Comment by josephrocca** [comment]
Hey @xl-sr, wondering if there's a chance you'll be releasing a pre-trained `fastgan_lite` model to compare alongside `fastgan` and `stylegan2`? I.e. all trained on the same dataset?

**Comment by AK391** [comment]
@xl-sr any update on this? 😀 https://github.com/autonomousvision/projected_gan/issues/48#issuecomment-1028940082

**Comment by xl-sr** [comment]
added :)

**Comment by AK391** [comment]
@xl-sr thanks, added the pokemon model :)

**Comment by AK391** [comment]
@xl-sr also could the models be added here? https://huggingface.co/autonomousvision, I can help with adding the models

**Comment by xl-sr** [comment]
done ;)
