### ISSUE TITLE
Creating video issue 

### ISSUE THREAD

**Issue by DavidRees87** [autonomousvision/projected_gan#52]
When using the default set up I am able to create a video without any problem. The issue I am having is when locating the .pkl file in my GDrive. The GDrive is connected, the training is being saved there and I am able to resume training with no problem. However when I use the path to the .pkl file neither images or video can be created. Do you have any ideas why this may be happening and any solutions?

Thank you for any help you can give, I greatly appreciate it.

**Comment by woctezuma** [comment]
Try to copy for .pkl file from your GDrive to your local session on Google Colab.

**Comment by xl-sr** [comment]
Hi David :) definitely try copying the pkl file to your local session. Also, could you post the error message you receive? I assume it simply does not find the pkl?

**Comment by DavidRees87** [comment]
Hi Axel,

Thank you for your reply and help. I did try that but kept getting disconnected before the large file could upload. However I did find a solution. 

For some reason if I ran the example project first and generated a video I was then able to generate one from the .pkl located on my Gdrive. I’m not sure why as everything else was exactly the same but it seems to have worked. 

Is it possible to change how the seeds transform in the videos generated? So that they change at a constant rate rather than speeding up and down?

Thank you so much for your help, I greatly appreciate it!

David

**Comment by DavidRees87** [comment]
When running the training with 1024x1024 images I get this error:

[/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py](https://6iiht1icr1u-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220207-060054-RC00_426876199#) in convert(t)
    895                 return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None,
    896                             non_blocking, memory_format=convert_to_format)
--> 897             return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
    898 
    899         return self._apply(convert)

RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 15.90 GiB total capacity; 14.87 GiB already allocated; 27.75 MiB free; 14.87 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF



I have Colab Pro+ and it doesn't look like there is a lack of memory. Any suggestions on what I can do?

Thanks

**Comment by DavidRees87** [comment]
Thank you, #5 worked. 

I also tried using 4096x4096 images but got an error message. Are those files too large to use?

Thanks

David

**Comment by xl-sr** [comment]
yes, those are very likely too large and need some special treatment.
