### ISSUE TITLE
Colab not working on 

### ISSUE THREAD

**Issue by manzke** [autonomousvision/projected_gan#53]
Hey,
I'm trying to reproduce your results right now and I'm playing around with your notebook. You are using conda for managing the dependencies and this is not represented in it. timm and dill don't seem to be enough.
Colab fails with missing imports.

Any plans to support Google Colab completely? (or a way to use the env yml to install them)

**Comment by xl-sr** [comment]
moved discussion to https://github.com/autonomousvision/projected_gan/issues/54
