### ISSUE TITLE
network pkls should be versioned

### ISSUE THREAD

**Issue by manzke** [autonomousvision/projected_gan#55]
Took me awhile to figure out that the network pkl is overwritten. I think it should be versioned (checkpoint) like with all other implementations. Especially where GANs are horrible to train, you never know 100% which was the right point.

**Comment by woctezuma** [comment]
> **Q:** Please add a commandline parameter that a new pkl file is saved per snapshot, as is the case in normal stylegan.

> **A:** I won't add this feature, since keeping the best and most recent model is enough for most use cases. But feel free to create a fork and add it yourself. It is as simple as adding

```python
snapshot_pkl = os.path.join(run_dir, f'network-snapshot-{cur_nimg//1000:06d}.pkl')
if rank == 0:
with open(snapshot_pkl, 'wb') as f:
    dill.dump(snapshot_data, f)
```

after this line: 

https://github.com/autonomousvision/projected_gan/blob/a9817c8b6722b28f843fa18d605779d706f3e8bb/training/training_loop.py#L391

Reference:
- https://github.com/autonomousvision/projected_gan/issues/45#issuecomment-1014252107

**Comment by xl-sr** [comment]
see my answer in https://github.com/autonomousvision/projected_gan/issues/45#issuecomment-1014252107
