### ISSUE TITLE
The .pkl file

### ISSUE THREAD

**Issue by DavidRees87** [autonomousvision/projected_gan#59]
When trying to use the .pkl file with other stylegan programmes it can't be read properly. Is there a way to use the trained model created with other programmes?

**Comment by xl-sr** [comment]
I'll need some more information to help you. Where are the models from that you are trying to use? What error message do you get?

**Comment by DavidRees87** [comment]
Can I give you any further information? Sorry if I am missing something simple, just trying to figure how to project an image into latent space using projected_gan in the same way you can with stylegan2_ada. Or if this is not possible

Many thanks

**Comment by woctezuma** [comment]
I am not sure if you can use the .pkl file created by `autonomousvision/projected_gan` with the [projector script](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/main/projector.py) of the official repository.

**Comment by DavidRees87** [comment]
Thank you, that is what I thought but I wanted to check I hadn't missed something. If you know of anyway to convert the .pkl file or a smart work around please let me know. Thank you for your help :)
