### ISSUE TITLE
cannot import name 'misc' from 'torch_utils' (legacy.py)

### ISSUE THREAD

**Issue by Nanboy-Ronan** [autonomousvision/projected_gan#60]
I followed this instruction (https://github.com/autonomousvision/projected_gan/issues/4#issuecomment-982990695) to install dependencies for styleGAN with conda, and pip installed timm dill psutils. However, I get the following error: cannot import name 'misc' from 'torch_utils'.

I then tried pip install torch-utils. Then I can import torch_utils. But it seems like there is no such misc class in the torch_utils module. I wonder if anyone has the same problem. If you can run this locally, how to build the environment?

**Comment by Nanboy-Ronan** [comment]
It is one of the folder included. Should solved by checking environment path.

**Comment by bottle0228** [comment]
Hello, I also encountered this problem. How did you solve it?

**Comment by woctezuma** [comment]
It is this file: https://github.com/autonomousvision/projected-gan/blob/main/torch_utils/misc.py
