### ISSUE TITLE
CLVR dataset visualization bug? <after python dataset_tool.py>

### ISSUE THREAD

**Issue by dongzhuoyao** [autonomousvision/projected_gan#61]
I tried to unzip the .zip file. I got this.

![aa](https://user-images.githubusercontent.com/13537104/155352892-c28cbf23-4d22-4dce-8e83-33e0beecb749.png)

Anyone experience the same?

**Comment by dongzhuoyao** [comment]
I change those two lines:

https://github.com/autonomousvision/projected_gan/blob/main/dataset_tool.py#L241


https://github.com/autonomousvision/projected_gan/blob/main/dataset_tool.py#L448

from "RGB" to "RGBA". 

it becomes normal now, so it's a dataset bug?

![a100](https://user-images.githubusercontent.com/13537104/155354779-393037b9-e8d2-449f-b2a4-888e5fbbb772.png)

**Comment by dongzhuoyao** [comment]
code snippet to reproduce:

```
import PIL.Image
import numpy as np
import io, os

fname = './CLEVR_v1.0/images/train/CLEVR_train_000000.png'
img  = PIL.Image.open(fname)

img.save('aaa.png')

img = np.array(img)

img = PIL.Image.fromarray(img, 'RGBA')

img.save('aa.png')
img = img.resize((128, 128), PIL.Image.LANCZOS)

#img.save('b.png')
img = np.array(img)


channels=3
img = PIL.Image.fromarray(img, { 1: 'L', 3: 'RGBA' }[channels])

img.save('a100.png')
```

**Comment by xl-sr** [comment]
seems like a dataset bug :)
