### ISSUE TITLE
Qusetion about the architecture of the CSM

### ISSUE THREAD

**Issue by TheshowN** [autonomousvision/projected_gan#69]
Hey, your work is wonderful！And I have some questions here.
1. You said in the paper that "CSM  extends  CCM  with  random  3×3  convolutions",  but there is only a 1x1 conv in the FeatureFusionBlock? Are there any insights?
2. Did you try using VGG as Pretrained Feature Network? If not, why you did't try it?
3. Is there any analysis about why DeiT is better than ViT as Pretrained Feature Network?
4. When you choose DeiT as Pretrained Feature Network, the sizes of features from layers {3, 6, 9, 12} is [B, 196, 384]. How did you process them in the CSM?

Thank you in advance!

**Comment by xl-sr** [comment]
Hey :)

1. see here: https://github.com/autonomousvision/projected_gan/issues/20
2. Yes, we tried, it works but a bit worse. Results are [here](https://openreview.net/forum?id=fUxqIofPPi), CTRL+F for "vgg"
3. Generally, smaller networks work better as we described in the paper, why is still an open research question ;)
4. You can resize them to correspond to spatial maps, we follow the procedure proposed in DPT (https://github.com/isl-org/DPT)

**Comment by TheshowN** [comment]
Thank you again for your quick reply!
Regarding the 4. question, so you use the "Reassemble" modules from DPT to process the features from the ViT and DeiT?  So are the parameters of the "Reassemble" modules trained during PG training?

**Comment by xl-sr** [comment]
Basically, you plug this line
https://github.com/isl-org/DPT/blob/788a40f309128c7c4ffce02ce9a9e081f2a75e4a/dpt/models.py#L72

here (instead of ```self.pretrained.layer{i}```)
https://github.com/autonomousvision/projected_gan/blob/521eee5051cb51834393cda8aa61450db01113f0/pg_modules/projector.py#L114

Everything after remains as is (CCM +CSM). All parameters remain fixed.
