### ISSUE TITLE
Question about FeatureFusionBlock

### ISSUE THREAD

**Issue by Torment123** [autonomousvision/projected_gan#73]
Hi, thank you for this very interesting work. I'm currently studying the code of projected-GAN, I have a question regarding the code of the FeatureFusionBlock module that used for fusion the feautres in csm. In the paper it says the fusion is consists of 3x3 convolutions and bilinear upsampling, but in the code I found the forward part of FeatureFusionBlock is actually upsampling + 1x1 conv ('self.out_conv'), so if my understand is correct, this implementation is different from the paper? I saw there is a ResidualConvUnit which executes the 3x3 conv and addition operation, but is not used in the FeatureFusionBlock, could you help me clarify whether I should change this part of code to be align with the description on paper (3x3 conv instead of 1x1) for better performance? thanks

**Comment by woctezuma** [comment]
- https://github.com/autonomousvision/projected_gan/issues/20#issuecomment-989150148

**Comment by xl-sr** [comment]
see issue above
