### ISSUE TITLE
FID evaluated on the pretrained model pkl has large difference with the reported FIDs

### ISSUE THREAD

**Issue by Zhendong-Wang** [autonomousvision/projected_gan#75]
Hi,

I tried to use the `calc_metrics.py` to compute the FID score of the provided pretrianed model to reproduce the reported values. However, I got large mismatchings, for example, I got 2.27 for LSUN-Bedroom and 3.41 for LSUN-Church from the pretrained model pkls. Are they the correct values that I should get? 

BTW, will you release the pretrained models for AFHQ-Cat, AFHQ-Dog and AFHQ-Wild datasets. 

Thanks!

**Comment by xl-sr** [comment]
These should be the correct pkls, the reported FIDs are calculated with this repo. Maybe there is a minor difference in how you prepared the data.
