### ISSUE TITLE
Which GAN did you use?

### ISSUE THREAD

**Issue by nailcankara** [autonomousvision/projected_gan#78]
In which cfg did you get the best results with Projected Gan? Did you use StlyeGan2 on large datasets and FastGan on small datasets, or did you use FastGan on both?

![image](https://user-images.githubusercontent.com/53586899/167269022-3973bf33-b1a9-481d-8eb9-03af6223f6c8.png)

**Comment by xl-sr** [comment]
As described in the paper, for these experiments we use FastGAN.
