### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by diamond0910** [autonomousvision/projected_gan#79]
I would like to know the approximate training time required to get each result in this table? Thank you!

![image](https://user-images.githubusercontent.com/43036573/167378174-8df0398f-6f17-4180-9e88-d142e2b78e04.png)

**Comment by diamond0910** [comment]
Is there a sec/kimg for different number of GPUs for different resolutions like stylegan2-ada?

![image](https://user-images.githubusercontent.com/43036573/167406648-78832abf-4616-47ed-9e73-ca66d2639589.png)

**Comment by diamond0910** [comment]
I trained on 256 resolution in 4 NVIDIA TITAN RTX GPUs. The sec/kimg is about 80 which is so slow compared to stylegan2-ada.

![image](https://user-images.githubusercontent.com/43036573/167406844-1ac3e78f-5d15-4dcb-b785-1368b48d9622.png)

**Comment by xl-sr** [comment]
This seems very slow, with your setup it should be around 10 sec/kings Maybe you can post you config file here?
