### ISSUE TITLE
Question on Loss function 

### ISSUE THREAD

**Issue by ck6397** [autonomousvision/projected_gan#82]
Hi! I must say that your paper is truly inspired. I have a query though,
In the paper you have mentioned that you have used minimax objective function which also includes the log term. But in the code module loss.py I am not able to find the same. Can you help me understand how the loss function is working?

**Comment by woctezuma** [comment]
Maybe related:
- https://github.com/autonomousvision/stylegan_xl/issues/28#issuecomment-1098770473

**Comment by ck6397** [comment]
Thanks!
