### ISSUE TITLE
What kind of data and tasks does SingleDiscCond anticipate?

### ISSUE THREAD

**Issue by mittu1008** [autonomousvision/projected_gan#83]
I have a feeling that the SingleDiscCond class is not used in the dataset used in your paper or in the assignment you are working on.
It also seems to me that you would not use it even if you start learning as per the example in the README.
What is SingleDiscCond used for?

**Comment by xl-sr** [comment]
see how it's used in the follow-up project: https://github.com/autonomousvision/stylegan_xl

**Comment by mittu1008** [comment]
thanks!
