### ISSUE TITLE
how to use discriminator

### ISSUE THREAD

**Issue by Salmashi** [autonomousvision/projected_gan#84]
from pg_modules.discriminator import ProjectedDiscriminator
D = ProjectedDiscriminator()
G = network_G()
fake_img = G(z)
real_img = real_img

We will use projected GAN in our project, the front is our pseudo-code, next how to use D network ? could you give us a pseudo-code for reference?

**Comment by xl-sr** [comment]
You can look at the code in the repo, everything is there. Don't let me do your work :)
