### ISSUE TITLE
Self-supervised feature extractor?

### ISSUE THREAD

**Issue by adambielski** [autonomousvision/projected_gan#85]
Hi @xl-sr and others using this repo,
I was wondering, did you try/have any success using self-supervised networks as a feature extractor? Any hints which networks would work best?
Unfortunately there are no self-supervised efficientnets lite, I wonder if any other choices would do

**Comment by woctezuma** [comment]
In general, I like [DINO](https://github.com/facebookresearch/dino).

**Comment by adambielski** [comment]
@woctezuma I like it too ;) but does it work well in the projected discriminator setting? Have you tried?

**Comment by woctezuma** [comment]
> @woctezuma I like it too ;) but does it work well in the projected discriminator setting? Have you tried?

Sorry, I have not tried in this specific setting.
